# Generated by Django 5.2.6 on 2025-09-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "driver",
                    models.CharField(
                        choices=[
                            ("postgres", "PostgreSQL"),
                            ("mysql", "MySQL/MariaDB"),
                            ("sqlite", "SQLite"),
                            ("mssql", "Microsoft SQL Server"),
                        ],
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255, null=True)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("database", models.CharField(blank=True, max_length=255, null=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "secret_encrypted",
                    models.TextField(
                        help_text="Stores the encrypted database password or other sensitive connection info."
                    ),
                ),
                (
                    "options_json",
                    models.JSONField(
                        default=dict,
                        help_text="Optional JSON for extra connection parameters.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "name")},
            },
        ),
    ]
