# Generated by Django 5.2.6 on 2025-09-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("connections", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaCache",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="schema_cache",
                        serialize=False,
                        to="connections.connection",
                    ),
                ),
                (
                    "payload_json",
                    models.JSONField(
                        help_text="The full introspected schema: tables, columns, PKs, FKs, etc."
                    ),
                ),
                (
                    "graph_json",
                    models.JSONField(
                        help_text="A lightweight graph representation (nodes and edges) for the ERD."
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        help_text="A hash of the schema content to detect changes.",
                        max_length=64,
                    ),
                ),
                (
                    "refreshed_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp of the last successful introspection.",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
